# [10강] TensorFlow로 파일에서 데이터 읽어오기

#### 파일에서 데이터 읽어오는 방법!

In [17]:
import tensorflow as tf
import numpy as np #numpy 라이브러리를 이용
tf.set_random_seed(777)

In [18]:
xy = np.loadtxt('C:/Users/JIHYE/Desktop/data-01-test-score.csv', delimiter=',', dtype=np.float32) #loadtxt로 파일을 불러온다. ','로 구분하며 데이터 타입도 알려 준다.
#C:/Users/JIHYE/Desktop/ 는 바탕화면에 있는 파일을 불러오는 경로이다.
#파일의 텍스트를 x, y의 2차원 배열로 읽어 온다.
x_data = xy[:,0:-1] #2차원 배열 속의 각 배열들 전체의 인덱스들 중 처음부터 마지막 인덱스 전까지 x_data에 넣는다.
y_data = xy[:, [-1]] #2차원 배열 속의 각 배열들 전체의 인덱스들 중 마지막 인덱스만 y_data에 넣는다.

In [19]:
print(x_data.shape, x_data, len(x_data)) #x_data의 모양, x_data, 길이를 프린트한다.
print(y_data.shape, y_data) #y_data의 모양, y_data를 프린트한다.

(6, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]] 6
(6, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]]


#### 아래는 원래와 동일하다!

In [20]:
X= tf.placeholder(tf.float32, shape=[None, 3]) #요인이 3개 이므로
Y= tf.placeholder(tf.float32, shape=[None, 1]) #결과가 1개 이므로

In [21]:
W = tf.Variable(tf.random_normal([3,1]), name='weight') #요인이 3개 이므로
b = tf.Variable(tf.random_normal([1]), name='bias') #결과가 1개 이므로

In [22]:
hypothesis = tf.matmul(X, W) + b #Hypothesis를 매트릭스를 이용해 만듦

In [23]:
cost = tf.reduce_mean(tf.square(hypothesis - Y)) #cost
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #GradientDescent로 cost를 깎아 내려감
train = optimizer.minimize(cost) #cost를 optimizer 시킴

In [24]:
sess = tf.Session() #세션
sess.run(tf.global_variables_initializer())

In [25]:
for step in range(2001): #학습
    cost_val, hy_val, _= sess.run(
    [cost, hypothesis, train],
    feed_dict = {X:x_data, Y:y_data})
    if step%10 == 0:
        print(step, "Cost: ", cost_val,
             "\nPrediction:\n", hy_val)

0 Cost:  106592.73 
Prediction:
 [[-149.32951]
 [-187.5982 ]
 [-180.82347]
 [-196.6437 ]
 [-145.01945]
 [-106.80911]]
10 Cost:  20.035086 
Prediction:
 [[155.00716]
 [178.32414]
 [179.65617]
 [195.9291 ]
 [134.10411]
 [ 98.96723]]
20 Cost:  15.075046 
Prediction:
 [[157.0528  ]
 [180.81023 ]
 [182.09154 ]
 [198.58269 ]
 [136.00589 ]
 [100.374565]]
30 Cost:  15.003414 
Prediction:
 [[157.05122 ]
 [180.83488 ]
 [182.10202 ]
 [198.59554 ]
 [136.03012 ]
 [100.397766]]
40 Cost:  14.932426 
Prediction:
 [[157.03584 ]
 [180.84288 ]
 [182.09612 ]
 [198.59056 ]
 [136.04163 ]
 [100.411545]]
50 Cost:  14.861908 
Prediction:
 [[157.0204 ]
 [180.85071]
 [182.09013]
 [198.58543]
 [136.053  ]
 [100.4252 ]]
60 Cost:  14.791779 
Prediction:
 [[157.00502 ]
 [180.85854 ]
 [182.08415 ]
 [198.58034 ]
 [136.06435 ]
 [100.438835]]
70 Cost:  14.722149 
Prediction:
 [[156.9897 ]
 [180.86633]
 [182.07822]
 [198.57527]
 [136.07567]
 [100.4524 ]]
80 Cost:  14.652984 
Prediction:
 [[156.97444]
 [180.87411]
 [182.0

840 Cost:  10.497241 
Prediction:
 [[155.95108 ]
 [181.39685 ]
 [181.67712 ]
 [198.22382 ]
 [136.85234 ]
 [101.365005]]
850 Cost:  10.454711 
Prediction:
 [[155.93925]
 [181.40292]
 [181.67258]
 [198.21971]
 [136.86131]
 [101.37529]]
860 Cost:  10.412549 
Prediction:
 [[155.92749]
 [181.40895]
 [181.66806]
 [198.21562]
 [136.87024]
 [101.38552]]
870 Cost:  10.370593 
Prediction:
 [[155.91576]
 [181.415  ]
 [181.66356]
 [198.21156]
 [136.87915]
 [101.39573]]
880 Cost:  10.328941 
Prediction:
 [[155.90408]
 [181.42099]
 [181.65906]
 [198.20749]
 [136.88803]
 [101.40591]]
890 Cost:  10.287553 
Prediction:
 [[155.89244]
 [181.42696]
 [181.65459]
 [198.20345]
 [136.8969 ]
 [101.41603]]
900 Cost:  10.246419 
Prediction:
 [[155.88084 ]
 [181.43294 ]
 [181.65016 ]
 [198.19942 ]
 [136.90573 ]
 [101.426125]]
910 Cost:  10.205531 
Prediction:
 [[155.86926]
 [181.43887]
 [181.6457 ]
 [198.19537]
 [136.91452]
 [101.43618]]
920 Cost:  10.164866 
Prediction:
 [[155.85773 ]
 [181.44481 ]
 [181.64128 ]

1620 Cost:  7.8644156 
Prediction:
 [[155.13943]
 [181.81584]
 [181.36728]
 [197.93504]
 [137.4785 ]
 [102.06479]]
1630 Cost:  7.838202 
Prediction:
 [[155.13036]
 [181.82057]
 [181.36383]
 [197.93172]
 [137.48564]
 [102.07253]]
1640 Cost:  7.812097 
Prediction:
 [[155.12128 ]
 [181.82529 ]
 [181.36038 ]
 [197.92839 ]
 [137.49277 ]
 [102.080246]]
1650 Cost:  7.786217 
Prediction:
 [[155.11227]
 [181.82999]
 [181.357  ]
 [197.92508]
 [137.49988]
 [102.08794]]
1660 Cost:  7.7604613 
Prediction:
 [[155.10327]
 [181.83466]
 [181.35359]
 [197.92178]
 [137.50697]
 [102.09559]]
1670 Cost:  7.7348704 
Prediction:
 [[155.0943 ]
 [181.83931]
 [181.35017]
 [197.91847]
 [137.51402]
 [102.10321]]
1680 Cost:  7.709425 
Prediction:
 [[155.08537 ]
 [181.84396 ]
 [181.34679 ]
 [197.91518 ]
 [137.52107 ]
 [102.110825]]
1690 Cost:  7.6841254 
Prediction:
 [[155.07645]
 [181.8486 ]
 [181.34343]
 [197.9119 ]
 [137.52809]
 [102.11839]]
1700 Cost:  7.6589966 
Prediction:
 [[155.06757]
 [181.85321]
 [181.3400

In [31]:
#학습한 값을 바탕으로 다른 값들을 예상할 수 있다.
print("Your score will be ", sess.run(hypothesis, feed_dict = {X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict = {X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[174.159]]
Other scores will be  [[173.91095]
 [180.7956 ]]
